#!/bin/bash

/home/rado/bin/sonar/bin/linux-x86-64/sonar.sh stop

mvn install -DskipTests
cp ./target/sonar-scoverage-plugin-0.1-SNAPSHOT.jar /home/rado/bin/sonar/extensions/plugins/

/home/rado/bin/sonar/bin/linux-x86-64/sonar.sh start
